server:
  port: 8084

spring:
  datasource:
    url: jdbc:sqlite:order-service.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${JWT_SECRET:change-me}

services:
  customer-url: ${CUSTOMER_SERVICE_URL:http://localhost:8082}
  product-url: ${PRODUCT_SERVICE_URL:http://localhost:8083}
  inventory-url: ${INVENTORY_SERVICE_URL:http://localhost:8085}
