spring:
  datasource:
    url: jdbc:sqlite:inventory-service.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8085

jwt:
  secret: ${JWT_SECRET:OrderManagerMicroservicesSharedJwtSecret2026!}

services:
  product-url: ${PRODUCT_SERVICE_URL:http://localhost:8083}
